apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp

resources:
  - frontend.yaml
  - frontend-service.yaml
  - frontend-route.yaml

images:
  - name: docker.io/aymankamell/myapp-frontend
    digest: sha256:cb42e33247aaf10d628d046d3fe6389d920fe89ebedd8b4dcc4d5039812c9c07
