apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp

resources:
  - backend.yaml
  - backend-service.yaml
  - backend-serviceaccount.yaml
  - role-app.yaml
  - rolebinding-app.yaml

images:
  - name: docker.io/aymankamell/myapp-backend
    digest: sha256:56bf2f666d46c008dfc7cc7f9375d73dc81717208cfd76297b39aa5da53e18ab
