apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp

resources:
  - backend.yaml
  - backend-service.yaml
  - backend-serviceaccount.yaml
  - role-app.yaml
  - rolebinding-app.yaml

images:
  - name: docker.io/aymankamell/myapp-backend
    digest: sha256:733f2033c7f4e69aa870e9b158f8ad96e43b735df054919caca657d0c98287e2
