apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp

resources:
  - backend.yaml
  - backend-service.yaml
  - backend-serviceaccount.yaml
  - role-app.yaml
  - rolebinding-app.yaml

images:
  - name: docker.io/aymankamell/myapp-backend
    digest: sha256:fe0b64f429a4b2afdbed2838b8be0e3df07cc5b54fa98969d30b7717e357b635
